-- Akensya multi-tenant Supabase schema
-- Run once in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  company text not null default 'DemoBrand',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.datasets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  dataset_name text not null check (
    dataset_name in ('customers','campaigns','transactions','interactions','sustainability')
  ),
  row_data jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists datasets_user_dataset_idx
  on public.datasets(user_id, dataset_name);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  entity text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists events_user_idx
  on public.events(user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.datasets enable row level security;
alter table public.events enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "datasets_select_own" on public.datasets;
create policy "datasets_select_own"
on public.datasets for select
using (auth.uid() = user_id);

drop policy if exists "datasets_insert_own" on public.datasets;
create policy "datasets_insert_own"
on public.datasets for insert
with check (auth.uid() = user_id);

drop policy if exists "datasets_delete_own" on public.datasets;
create policy "datasets_delete_own"
on public.datasets for delete
using (auth.uid() = user_id);

drop policy if exists "events_select_own" on public.events;
create policy "events_select_own"
on public.events for select
using (auth.uid() = user_id);

drop policy if exists "events_insert_own" on public.events;
create policy "events_insert_own"
on public.events for insert
with check (auth.uid() = user_id);

-- Automatically create a profile row for newly registered Supabase users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, company)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'company', 'DemoBrand')
  )
  on conflict (id) do update
    set email = excluded.email,
        company = excluded.company,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
