-- Akensya multi-tenant schema
-- Run this in Supabase SQL Editor before deploying.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  company_name text not null default 'My Brand',
  industry text,
  company_size text,
  goals jsonb not null default '[]'::jsonb,
  stack jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.datasets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  dataset_type text not null check (dataset_type in ('customers','campaigns','interactions','sustainability','transactions')),
  file_name text not null,
  content text not null,
  row_count integer not null default 0,
  columns jsonb not null default '[]'::jsonb,
  quality jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, dataset_type)
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  event_type text not null,
  entity text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.datasets enable row level security;
alter table public.events enable row level security;

-- Profiles
create policy "profiles_select_own" on public.profiles for select using (id = auth.uid());
create policy "profiles_insert_own" on public.profiles for insert with check (id = auth.uid());
create policy "profiles_update_own" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

-- Datasets: a brand can only see/change its own datasets.
create policy "datasets_select_own" on public.datasets for select using (user_id = auth.uid());
create policy "datasets_insert_own" on public.datasets for insert with check (user_id = auth.uid());
create policy "datasets_update_own" on public.datasets for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "datasets_delete_own" on public.datasets for delete using (user_id = auth.uid());

-- Events: users can write/read only their own events.
create policy "events_select_own" on public.events for select using (user_id = auth.uid());
create policy "events_insert_own" on public.events for insert with check (user_id = auth.uid());

-- Create profile automatically after signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, company_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'company_name','My Brand'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
